import { UserProfile, Product, StoreContext, StoreConfig } from './types';

export const MOCK_STORE_CONFIG: StoreConfig = {
  storeId: 'deco-merchant-store',
  storeName: 'Deco Fashion & Style (White-Label Store)',
  tagline: 'Canal de Vendas Agêntico Oficial • Powered by $Agent',
  currency: 'BRL',
  cashbackPercentage: 5,
  activeCoupons: [
    {
      code: 'DECO10',
      discountType: 'percentage',
      discountValue: 10,
      description: '10% OFF exclusivo no Canal Agêntico $Agent',
    },
    {
      code: 'AGENT50',
      discountType: 'fixed',
      discountValue: 50,
      description: 'R$ 50 OFF de bônus de primeira compra agêntica',
    }
  ],
  databaseDriver: 'mock',
  serverEndpoint: 'https://api.merchant-store.com.br',
};

export const MOCK_USER_PROFILES: UserProfile[] = [
  {
    id: 'user-ana',
    name: 'Ana Silva',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    badge: 'Compradora VIP • Saldo Cashback Ativo',
    sizes: {
      clothing: 'M',
      shoes: '37',
    },
    stylePreferences: ['Minimalista', 'Elegante', 'Casual Chic'],
    favoriteColors: ['Bege', 'Branco', 'Azul Marinho', 'Preto'],
    maxBudget: 450,
    restrictions: ['Algodão Orgânico', 'Sem Couro Animal'],
    gender: 'Feminino',
    walletBalance: 42.50,
  },
  {
    id: 'user-carlos',
    name: 'Carlos Eduardo',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    badge: 'Estilo Streetwear & Tech',
    sizes: {
      clothing: 'G',
      shoes: '42',
    },
    stylePreferences: ['Streetwear', 'Esportivo', 'Moderno'],
    favoriteColors: ['Preto', 'Cinza', 'Verde Militar'],
    maxBudget: 600,
    restrictions: ['Tecido Respirável'],
    gender: 'Masculino',
    walletBalance: 15.00,
  }
];

export const MOCK_STORE_PRODUCTS: Product[] = [
  {
    id: 'prod-001',
    name: 'Vestido Linho Pure Elegance',
    description: 'Vestido midi 100% linho orgânico com fenda discreta e caimento fluido.',
    price: 320,
    originalPrice: 420,
    category: 'Vestidos',
    availableSizes: ['P', 'M', 'G'],
    colors: ['Bege', 'Branco'],
    imageUrl: 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=600&auto=format&fit=crop&q=80',
    tags: ['Linho', 'Minimalista', 'Verão', 'Algodão Orgânico'],
    inStock: true,
    storeName: 'Deco Fashion',
    cashbackReward: 16.00,
  },
  {
    id: 'prod-002',
    name: 'Blazer Oversized Alfaiataria',
    description: 'Blazer estruturado em alfaiataria premium com abotoamento duplo.',
    price: 490,
    originalPrice: 590,
    category: 'Casacos & Blazers',
    availableSizes: ['PP', 'P', 'M', 'G'],
    colors: ['Preto', 'Azul Marinho'],
    imageUrl: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=600&auto=format&fit=crop&q=80',
    tags: ['Elegante', 'Trabalho', 'Sem Couro Animal'],
    inStock: true,
    storeName: 'Deco Fashion',
    cashbackReward: 24.50,
  },
  {
    id: 'prod-003',
    name: 'Camiseta Tech Cotton Breathable',
    description: 'Camiseta masculina com tecnologia anti-suor e elasticidade 4D.',
    price: 180,
    category: 'Camisetas',
    availableSizes: ['P', 'M', 'G', 'GG'],
    colors: ['Preto', 'Cinza', 'Verde Militar'],
    imageUrl: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=600&auto=format&fit=crop&q=80',
    tags: ['Tech', 'Streetwear', 'Esportivo', 'Tecido Respirável'],
    inStock: true,
    storeName: 'Deco Fashion',
    cashbackReward: 9.00,
  },
  {
    id: 'prod-004',
    name: 'Jaqueta Puffer Street Urban',
    description: 'Jaqueta puffer térmica à prova d’água com capuz removível.',
    price: 550,
    originalPrice: 680,
    category: 'Casacos & Blazers',
    availableSizes: ['M', 'G', 'GG'],
    colors: ['Preto', 'Verde Militar'],
    imageUrl: 'https://images.unsplash.com/photo-1544441893-675973e31985?w=600&auto=format&fit=crop&q=80',
    tags: ['Streetwear', 'Inverno'],
    inStock: true,
    storeName: 'Deco Fashion',
    cashbackReward: 27.50,
  },
  {
    id: 'prod-005',
    name: 'Vestido Seda Esmeralda Gala',
    description: 'Vestido longo de seda natural com decote sutil em V e acabamento impecável.',
    price: 980,
    originalPrice: 1200,
    category: 'Vestidos',
    availableSizes: ['P', 'M'],
    colors: ['Verde Esmeralda', 'Vinho'],
    imageUrl: 'https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=600&auto=format&fit=crop&q=80',
    tags: ['Festa', 'Sophisticated', 'Alta Costura'],
    inStock: true,
    storeName: 'Deco Fashion',
    cashbackReward: 49.00,
  },
  {
    id: 'prod-006',
    name: 'Calça Wide Leg Tailored',
    description: 'Calça de cintura alta em tecido leve com caimento amplo e elegante.',
    price: 290,
    category: 'Calças',
    availableSizes: ['36', '38', '40', '42'],
    colors: ['Bege', 'Preto'],
    imageUrl: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=600&auto=format&fit=crop&q=80',
    tags: ['Minimalista', 'Casual Chic'],
    inStock: true,
    storeName: 'Deco Fashion',
    cashbackReward: 14.50,
  }
];

export const MOCK_STORE_CONTEXT: StoreContext = {
  storeId: MOCK_STORE_CONFIG.storeId,
  storeName: MOCK_STORE_CONFIG.storeName,
  currency: MOCK_STORE_CONFIG.currency,
  catalog: MOCK_STORE_PRODUCTS,
  config: MOCK_STORE_CONFIG,
};
